name: 'study-db'

services:
  db:
    container_name: 'db-study'
    image: postgres:17.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db-study'
